modules: video: Fix DRM client lib dependency
Fix dependency for kmod-drm-client-lib module:
error: recursive dependency detected!
	symbol LINUX_6_18 is selected by PACKAGE_kmod-drm-client-lib
	symbol PACKAGE_kmod-drm-client-lib is selected by LINUX_6_18

Fixes: 444826b08d1c ("modules: video: introduce DRM client setup module")
Signed-off-by: Paweł Owoc <frut3k7@gmail.com>
Link: https://github.com/openwrt/openwrt/pull/23124
Signed-off-by: Robert Marko <robimarko@gmail.com>